<?php
/* Copyright (C) 2025 Henaxis */

/**
 * \file    custom/b2border/admin/downloadcss.php
 * \brief   Download CSS example file for B2B portal customization
 */

$res = 0;
foreach (array(
	dirname(dirname(dirname(__DIR__))).'/main.inc.php',
	dirname(dirname(dirname(dirname(__DIR__)))).'/main.inc.php',
	dirname(dirname(dirname(__DIR__))).'/htdocs/main.inc.php',
) as $_mainPath) {
	if (file_exists($_mainPath)) {
		$res = @include $_mainPath;
		if ($res) {
			break;
		}
	}
}
if (!$res) {
	die('Include of main fails');
}

// Admin-only download — $user->admin check is sufficient for a GET download
if (!$user->admin) {
	accessforbidden();
}

// Output CSS file as download
header('Content-Type: text/css; charset=utf-8');
header('Content-Disposition: attachment; filename="b2border-custom-example.css"');
header('Cache-Control: no-cache');

echo '/*
 * ============================================================
 * B2B Order Portal - CSS Customization Example
 * Generated by b2border module
 *
 * HOW TO USE:
 * 1. Copy the rules you want to customize
 * 2. Paste them in Admin > B2B Order Portal > Aspetto > CSS personalizzato
 * 3. Save and refresh the portal
 *
 * TIP: Start by overriding the CSS variables in :root to change
 * colors globally, then fine-tune individual components below.
 * ============================================================
 */


/* ======================================================
 * 1. CSS CUSTOM PROPERTIES (Variables)
 *    Override these to instantly restyle the entire portal
 * ====================================================== */
:root {
    /* --- Brand colors --- */
    /* Main accent: used for buttons, active nav, links, cart badge */
    --b2b-primary: #2e86de;
    /* Darker accent: used on hover states of primary elements */
    --b2b-primary-dark: #1a5fa8;
    /* Secondary / neutral: used for secondary buttons */
    --b2b-secondary: #576574;

    /* --- Semantic colors --- */
    --b2b-success: #27ae60;   /* In-stock badge, success messages */
    --b2b-danger:  #e74c3c;   /* Out-of-stock, delete, error messages */
    --b2b-warning: #f39c12;   /* Warning messages */

    /* --- Layout & surfaces --- */
    --b2b-bg:      #f5f6fa;   /* Page background */
    --b2b-white:   #ffffff;   /* Card / header surface */

    /* --- Typography --- */
    --b2b-text:       #2c3e50; /* Main body text */
    --b2b-text-light: #7f8c8d; /* Muted labels, secondary info */

    /* --- Borders & shadows --- */
    --b2b-border: #dfe6e9;
    --b2b-radius: 6px;
    --b2b-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);

    /* --- Container max-width --- */
    --b2b-container: 1200px;
}


/* ======================================================
 * 2. GLOBAL LAYOUT
 * ====================================================== */

/* Portal body (authenticated pages) */
body.b2b-portal {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    font-size: 15px;
    background: var(--b2b-bg);
    color: var(--b2b-text);
}

/* Login page body */
body.b2b-login-page {
    background: var(--b2b-primary);
}

/* Centered content wrapper */
.b2b-container {
    max-width: var(--b2b-container);
    margin: 0 auto;
    padding: 0 16px;
}

/* Main content area (between header and footer) */
.b2b-main {
    flex: 1;
    padding: 24px 0;
}


/* ======================================================
 * 3. HEADER
 * ====================================================== */

.b2b-header {
    background: var(--b2b-white);
    box-shadow: var(--b2b-shadow);
    position: sticky;
    top: 0;
    z-index: 100;
}

.b2b-header-inner {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 12px 0;
}

/* Logo text link (fallback when no logo image is set) */
.b2b-logo {
    font-size: 18px;
    font-weight: 700;
    color: var(--b2b-primary);
}

/* Logo image (when uploaded in Admin > Aspetto) */
.b2b-logo-img {
    max-height: 36px;
    max-width: 200px;
    object-fit: contain;
}


/* ======================================================
 * 4. NAVIGATION
 * ====================================================== */

.b2b-nav {
    display: flex;
    align-items: center;
    gap: 8px;
}

/* Nav link (Catalog, Cart) */
.b2b-nav-link {
    padding: 6px 12px;
    border-radius: var(--b2b-radius);
    color: var(--b2b-text);
    font-size: 14px;
    font-weight: 500;
}

.b2b-nav-link:hover {
    background: var(--b2b-bg);
    text-decoration: none;
}

.b2b-nav-link.active {
    background: var(--b2b-primary);
    color: var(--b2b-white);
}

/* Logged-in username display */
.b2b-nav-user {
    font-size: 13px;
    color: var(--b2b-text-light);
}

/* Logout link */
.b2b-logout {
    color: var(--b2b-danger);
}

/* Cart item count badge */
.b2b-cart-badge {
    background: var(--b2b-danger);
    color: var(--b2b-white);
    font-size: 11px;
    font-weight: 700;
    padding: 1px 6px;
    border-radius: 10px;
}

/* Mobile hamburger button */
.b2b-menu-toggle {
    display: none;
    border: 1px solid var(--b2b-border);
    border-radius: var(--b2b-radius);
    font-size: 20px;
    padding: 4px 10px;
    cursor: pointer;
}


/* ======================================================
 * 5. MESSAGES (errors / success)
 * ====================================================== */

.b2b-msg {
    padding: 10px 16px;
    margin: 8px 0;
    border-radius: var(--b2b-radius);
    font-size: 14px;
}

.b2b-msg-error {
    background: #ffeaa7;
    color: #d63031;
    border-left: 4px solid var(--b2b-danger);
}

.b2b-msg-success {
    background: #d5f5e3;
    color: #1e8449;
    border-left: 4px solid var(--b2b-success);
}


/* ======================================================
 * 6. BUTTONS
 * ====================================================== */

.b2b-btn {
    display: inline-block;
    padding: 8px 18px;
    border: none;
    border-radius: var(--b2b-radius);
    font-size: 14px;
    font-weight: 600;
    cursor: pointer;
    text-align: center;
}

.b2b-btn-primary  { background: var(--b2b-primary);   color: var(--b2b-white); }
.b2b-btn-secondary{ background: var(--b2b-secondary);  color: var(--b2b-white); }
.b2b-btn-danger   { background: var(--b2b-danger);     color: var(--b2b-white); }

.b2b-btn-outline {
    background: var(--b2b-white);
    color: var(--b2b-text);
    border: 1px solid var(--b2b-border);
}

.b2b-btn-block { display: block; width: 100%; }
.b2b-btn-sm    { padding: 5px 12px; font-size: 13px; }


/* ======================================================
 * 7. FORMS
 * ====================================================== */

.b2b-form-group {
    margin-bottom: 16px;
}

.b2b-form-group label {
    display: block;
    margin-bottom: 6px;
    font-size: 14px;
    font-weight: 500;
}

.b2b-input,
.b2b-select {
    padding: 8px 12px;
    border: 1px solid var(--b2b-border);
    border-radius: var(--b2b-radius);
    font-size: 14px;
    color: var(--b2b-text);
    background: var(--b2b-white);
    width: 100%;
}

.b2b-input:focus,
.b2b-select:focus {
    outline: none;
    border-color: var(--b2b-primary);
    box-shadow: 0 0 0 3px rgba(46, 134, 222, 0.15);
}


/* ======================================================
 * 8. CATALOG - SEARCH BAR
 * ====================================================== */

.b2b-search-bar {
    margin-bottom: 16px;
}

.b2b-search-bar input {
    /* Inherits .b2b-input styles */
    padding: 10px 16px;
    font-size: 15px;
}


/* ======================================================
 * 9. CATALOG - CATEGORY FILTER BAR
 * ====================================================== */

.b2b-cat-bar {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
    margin-bottom: 20px;
}

.b2b-cat-btn {
    padding: 5px 14px;
    border-radius: 20px;
    font-size: 13px;
    border: 1px solid var(--b2b-border);
    background: var(--b2b-white);
    cursor: pointer;
}

.b2b-cat-btn.active {
    background: var(--b2b-primary);
    color: var(--b2b-white);
    border-color: var(--b2b-primary);
}


/* ======================================================
 * 10. CATALOG - PRODUCT GRID
 * ====================================================== */

.b2b-products-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
    gap: 20px;
    margin-bottom: 32px;
}

/* Product card */
.b2b-product-card {
    background: var(--b2b-white);
    border: 1px solid var(--b2b-border);
    border-radius: var(--b2b-radius);
    overflow: hidden;
    display: flex;
    flex-direction: column;
}

.b2b-product-card:hover {
    box-shadow: var(--b2b-shadow);
    transform: translateY(-2px);
    transition: all 0.2s;
}

/* Product image wrapper */
.b2b-product-img-wrap {
    aspect-ratio: 1;
    background: var(--b2b-bg);
    overflow: hidden;
}

.b2b-product-img {
    width: 100%;
    height: 100%;
    object-fit: contain;
}

/* Card body */
.b2b-product-info {
    padding: 12px;
    flex: 1;
    display: flex;
    flex-direction: column;
}

.b2b-product-ref {
    font-size: 11px;
    color: var(--b2b-text-light);
    margin-bottom: 4px;
}

.b2b-product-name {
    font-weight: 600;
    font-size: 14px;
    margin-bottom: 6px;
    color: var(--b2b-text);
}

/* Price */
.b2b-product-price {
    margin: 8px 0;
}

.b2b-price-ht {
    font-size: 16px;
    font-weight: 700;
    color: var(--b2b-primary);
}

.b2b-price-vat {
    font-size: 11px;
    color: var(--b2b-text-light);
}

/* Stock badge */
.b2b-stock-badge {
    display: inline-block;
    font-size: 11px;
    padding: 2px 8px;
    border-radius: 10px;
    font-weight: 600;
}

.b2b-stock-badge.in-stock {
    background: #d5f5e3;
    color: var(--b2b-success);
}

.b2b-stock-badge.out-of-stock {
    background: #fdecea;
    color: var(--b2b-danger);
}

/* Qty + add to cart */
.b2b-product-actions {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-top: auto;
    padding-top: 10px;
}

.b2b-qty-input {
    width: 60px;
    padding: 6px 8px;
    border: 1px solid var(--b2b-border);
    border-radius: var(--b2b-radius);
    font-size: 14px;
    text-align: center;
}


/* ======================================================
 * 11. CATALOG - PAGINATION
 * ====================================================== */

.b2b-pagination {
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 4px;
    margin-top: 24px;
}

.b2b-page-btn {
    padding: 6px 12px;
    border: 1px solid var(--b2b-border);
    border-radius: var(--b2b-radius);
    background: var(--b2b-white);
    cursor: pointer;
    font-size: 14px;
}

.b2b-page-btn.active {
    background: var(--b2b-primary);
    color: var(--b2b-white);
    border-color: var(--b2b-primary);
}


/* ======================================================
 * 12. PRODUCT DETAIL
 * ====================================================== */

.b2b-product-detail {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 32px;
}

.b2b-product-detail-img {
    width: 100%;
    border-radius: var(--b2b-radius);
    border: 1px solid var(--b2b-border);
}

.b2b-product-detail-info {
    padding: 8px 0;
}


/* ======================================================
 * 13. CART
 * ====================================================== */

.b2b-cart-table {
    width: 100%;
    border-collapse: collapse;
    background: var(--b2b-white);
    border-radius: var(--b2b-radius);
    overflow: hidden;
    box-shadow: var(--b2b-shadow);
}

.b2b-cart-table th {
    padding: 12px 16px;
    background: var(--b2b-bg);
    text-align: left;
    font-size: 13px;
    color: var(--b2b-text-light);
    font-weight: 600;
}

.b2b-cart-table td {
    padding: 14px 16px;
    border-top: 1px solid var(--b2b-border);
    vertical-align: middle;
}

.b2b-cart-total {
    text-align: right;
    margin-top: 16px;
    padding: 16px;
    background: var(--b2b-white);
    border-radius: var(--b2b-radius);
}

.b2b-cart-actions {
    display: flex;
    justify-content: flex-end;
    gap: 12px;
    margin-top: 16px;
}


/* ======================================================
 * 14. CHECKOUT
 * ====================================================== */

.b2b-checkout-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 24px;
}

.b2b-checkout-summary,
.b2b-checkout-form {
    background: var(--b2b-white);
    border-radius: var(--b2b-radius);
    padding: 24px;
    box-shadow: var(--b2b-shadow);
}


/* ======================================================
 * 15. ORDER CONFIRMATION
 * ====================================================== */

.b2b-confirmation {
    text-align: center;
    padding: 48px 24px;
    background: var(--b2b-white);
    border-radius: var(--b2b-radius);
    max-width: 600px;
    margin: 0 auto;
}

.b2b-confirmation-icon {
    font-size: 64px;
    margin-bottom: 16px;
}


/* ======================================================
 * 16. LOGIN PAGE
 * ====================================================== */

/* Login page wrapper (full-screen) */
.b2b-login-wrapper {
    display: flex;
    align-items: center;
    justify-content: center;
    min-height: 100vh;
    padding: 24px;
}

/* Login card */
.b2b-login-box {
    background: var(--b2b-white);
    border-radius: var(--b2b-radius);
    padding: 40px;
    width: 100%;
    max-width: 400px;
    box-shadow: 0 4px 24px rgba(0, 0, 0, 0.15);
}

/* Logo above login title */
.b2b-login-logo {
    text-align: center;
    margin-bottom: 16px;
}

.b2b-login-logo img {
    max-width: 180px;
    max-height: 80px;
    object-fit: contain;
}

.b2b-login-title {
    font-size: 22px;
    font-weight: 700;
    text-align: center;
    margin-bottom: 4px;
    color: var(--b2b-text);
}

.b2b-login-subtitle {
    font-size: 14px;
    color: var(--b2b-text-light);
    text-align: center;
    margin-bottom: 28px;
}


/* ======================================================
 * 17. FOOTER
 * ====================================================== */

.b2b-footer {
    background: var(--b2b-white);
    border-top: 1px solid var(--b2b-border);
    padding: 16px 0;
    font-size: 13px;
    color: var(--b2b-text-light);
    text-align: center;
    margin-top: auto;
}

.b2b-footer-powered {
    font-size: 12px;
    color: var(--b2b-text-light);
    margin-top: 4px;
}


/* ======================================================
 * 18. TABLES (cart, product lists)
 * ====================================================== */

.b2b-table {
    width: 100%;
    border-collapse: collapse;
}

.b2b-table th {
    padding: 10px 12px;
    background: var(--b2b-bg);
    font-size: 12px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    color: var(--b2b-text-light);
    text-align: left;
    border-bottom: 2px solid var(--b2b-border);
}

.b2b-table td {
    padding: 12px;
    border-bottom: 1px solid var(--b2b-border);
    vertical-align: middle;
}


/* ======================================================
 * 19. RESPONSIVE - MOBILE (max-width: 768px)
 * ====================================================== */

@media (max-width: 768px) {
    /* Show hamburger, hide nav by default */
    .b2b-menu-toggle {
        display: block;
    }

    .b2b-nav {
        display: none;
        position: absolute;
        top: 60px;
        left: 0;
        right: 0;
        background: var(--b2b-white);
        flex-direction: column;
        padding: 12px 16px;
        box-shadow: var(--b2b-shadow);
    }

    .b2b-nav.open {
        display: flex;
    }

    /* Single column product grid on mobile */
    .b2b-products-grid {
        grid-template-columns: repeat(2, 1fr);
        gap: 12px;
    }

    /* Stack checkout/product detail on mobile */
    .b2b-checkout-grid,
    .b2b-product-detail {
        grid-template-columns: 1fr;
    }
}

@media (max-width: 480px) {
    .b2b-products-grid {
        grid-template-columns: 1fr;
    }
}


/* ======================================================
 * 20. EXAMPLE CUSTOMIZATIONS
 *    Uncomment and adapt what you need
 * ====================================================== */

/*
 * Example: Dark theme
 *
:root {
    --b2b-bg:    #1a1a2e;
    --b2b-white: #16213e;
    --b2b-text:  #e0e0e0;
    --b2b-border: #2d3561;
}
*/

/*
 * Example: Green brand
 *
:root {
    --b2b-primary:      #27ae60;
    --b2b-primary-dark: #1e8449;
}
*/

/*
 * Example: Larger product cards
 *
.b2b-products-grid {
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
}
*/

/*
 * Example: Hide product descriptions in catalog
 *
.b2b-product-desc {
    display: none;
}
*/
';
exit;
